---
- name: Install Confluent-Kafka
  hosts: localhost
  serial: 1
  become: false
  tasks:

  - name: Connect to the cluster
    include: connection.yml

  - name: Create a group for ZooKeeper
    dcos_iam_group:
      gid: confluent-zookeeper-group
      description: Permissions for ZooKeeper
      state: present
      permissions:
        - rid: dcos:mesos:master:framework:role:confluent-zookeeper-role
          action: create
        - rid: dcos:mesos:master:reservation:role:confluent-zookeeper-role
          action: create
        - rid: dcos:mesos:master:volume:role:confluent-zookeeper-role
          action: create
        - rid: dcos:mesos:master:task:user:nobody
          action: create
        - rid: dcos:mesos:master:reservation:principal:confluent-zookeeper
          action: delete
        - rid: dcos:mesos:master:volume:principal:confluent-zookeeper
          action: delete

  - name: Create service account for ZooKeeper
    dcos_iam_serviceaccount:
      sid: confluent-zookeeper
      description: 'ZooKeeper Service Account'
      secret_path: confluent-zookeeper/secret
      groups: 
        - confluent-zookeeper-group
      state: present

  - name: Ensure ZooKeeper is installed
    dcos_package:
      name: confluent-zookeeper
      app_id: confluent-zookeeper
      version: 2.4.0-4.0.0e
      state: present
      options:
        {
          "service": {
            "name": "confluent-zookeeper",
            "service_account": "confluent-zookeeper",
            "service_account_secret": "confluent-zookeeper/secret" 
          }
      }

  - name: Create a group for Kafka
    dcos_iam_group:
      gid: confluent-kafka-group
      description: Permissions for Kafka
      state: present
      permissions:
        - rid: dcos:mesos:master:framework:role:confluent-kafka-role
          action: create
        - rid: dcos:mesos:master:reservation:role:confluent-kafka-role
          action: create
        - rid: dcos:mesos:master:volume:role:confluent-kafka-role
          action: create
        - rid: dcos:mesos:master:task:user:nobody
          action: create
        - rid: dcos:mesos:master:reservation:principal:confluent-kafka
          action: delete
        - rid: dcos:mesos:master:volume:principal:confluent-kafka
          action: delete
        - rid: dcos:secrets:default:/confluent-kafka/*
          action: full
        - rid: dcos:secrets:list:default:/confluent-kafka
          action: read
        - rid: dcos:adminrouter:ops:ca:rw
          action: full
        - rid: dcos:adminrouter:ops:ca:ro
          action: full
  
  - name: Create service account for Kafka
    dcos_iam_serviceaccount:
      sid: confluent-kafka
      description: 'Kafka Service Account'
      secret_path: confluent-kafka/secret
      groups: 
        - confluent-kafka-group
      state: present

  - name: Ensure Kafka is installed
    dcos_package:
      name: confluent-kafka
      app_id: confluent-kafka
      version: 2.4.0-4.1.1
      state: present
      options:
        {
          'service': {
            'name': 'confluent-kafka',
            'service_account': 'confluent-kafka',
            'service_account_secret': 'confluent-kafka/secret',
            "security": {
              "ssl_authentication": {
                "enabled": true
              },
              "transport_encryption": {
                "enabled": true
              }
            }
          },
          "brokers": {
            "port_tls": 9092
          },
          'kafka': {
            'kafka_zookeeper_uri': 'zookeeper-0-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-1-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-2-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140'
          }
        }

  - name: Ensure Confluent Control Center is installed
    dcos_package:
      name: confluent-control-center
      app_id: control-center
      version: 1.1.1-4.1.1
      state: present
      options:
        {
          "control-center": {
            "name": "control-center",
            "listener_protocol": "http"
          },
          "kafka": {
            "bootstrap_servers": "broker-tls.confluent-kafka.l4lb.thisdcos.directory:9093",
            "zookeeper_connect": "zookeeper-0-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-1-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-2-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140",
            "client_security_protocol": "SSL"
          }
        }

  - name: Ensure Confluent Schema Registry is installed
    dcos_package:
      name: confluent-schema-registry
      app_id: schema-registry
      version: 1.1.0-4.0.0
      state: present
      options:
        {
          "registry": {
            "name": "schema-registry",
            "zookeeper_namespace": "dcos-service-confluent-kafka/schema-registry",
            "listener_protocol": "http"
          },
          "kafka": {
            "zookeeper_connect": "zookeeper-0-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-1-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-2-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140",
            "client_security_protocol": "SSL"
          }
        }

  - name: Ensure Confluent Connect is installed
    dcos_package:
      name: confluent-connect
      app_id: connect
      version: 1.1.1-4.1.1
      state: present
      options:
        {
          "connect": {
            "name": "connect"
          },
          "kafka": {
            "bootstrap_servers": "broker-tls.confluent-kafka.l4lb.thisdcos.directory:9093",
            "zookeeper_connect": "zookeeper-0-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-1-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-2-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140",
            "client_security_protocol": "SSL"
          },
          "schema-registry": {
            "url": "http://schema-registry.marathon.l4lb.thisdcos.directory:8081"
          }
        }

  - name: Ensure Confluent REST Proxy is installed
    dcos_package:
      name: confluent-rest-proxy
      app_id: rest-proxy
      version: 1.1.1-4.1.1
      state: present
      options:
        {
          "rest-proxy": {
            "name": "rest-proxy"
          },
          "kafka": {
            "bootstrap_servers": "broker-tls.confluent-kafka.l4lb.thisdcos.directory:9093",
            "zookeeper_connect": "zookeeper-0-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-1-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140,zookeeper-2-server.confluent-zookeeper.autoip.dcos.thisdcos.directory:1140",
            "client_security_protocol": "SSL"
          },
          "schema-registry": {
            "url": "http://schema-registry.marathon.l4lb.thisdcos.directory:8081"
          }
        }