---
- name: Install Elastic
  hosts: localhost
  serial: 1
  become: false
  tasks:

  - name: Connect to the cluster
    include: connection.yml

  - name: Create a group for Elastic
    dcos_iam_group:
      gid: elastic-group
      description: Permissions for Elastic
      state: present
      permissions:
        - rid: dcos:mesos:master:framework:role:elastic-role
          action: create
        - rid: dcos:mesos:master:reservation:role:elastic-role
          action: create
        - rid: dcos:mesos:master:volume:role:elastic-role
          action: create
        - rid: dcos:mesos:master:task:user:nobody
          action: create
        - rid: dcos:mesos:master:reservation:principal:elastic
          action: delete
        - rid: dcos:mesos:master:volume:principal:elastic
          action: delete
        - rid: dcos:secrets:default:/elastic/*
          action: full
        - rid: dcos:secrets:list:default:/elastic
          action: read
        - rid: dcos:adminrouter:ops:ca:rw
          action: full
        - rid: dcos:adminrouter:ops:ca:ro
          action: full

  - name: Create service account for Elastic
    dcos_iam_serviceaccount:
      sid: elastic
      description: 'Elastic Service Account'
      secret_path: elastic/secret
      groups: 
        - elastic-group
      state: present

  - name: Ensure Elastic is installed
    dcos_package:
      name: elastic
      app_id: elastic
      version: 2.7.0-6.8.1
      state: present
      options:
        {
            "service": {
                "service_account": "elastic",
                "service_account_secret": "elastic/secret",
                "security": {
                    "transport_encryption": {
                        "enabled": true
                    }
                }
            }, 
            "elasticsearch": {
              "health_user": "elastic",
              "health_user_password": "CviBT1vfUGVaWDl6idka",
              "xpack_enabled": true,
              "xpack_security_enabled": true
            },
            "ingest_nodes": {
              "count": 1
            }  
        }

  - name: Wait for master-0
    command: dcos task exec elastic__master-0-node sleep 30
    retries: 3
    delay: 3
    register: result
    until: result.rc == 0

  - name: Run password script
    command: dcos task exec elastic__master-0-node sh -c 'export JAVA_HOME=$(ls -d ${MESOS_SANDBOX}/jdk*/); export ELASTICSEARCH_PATH=$(ls -d ${MESOS_SANDBOX}/elasticsearch-*/); ${ELASTICSEARCH_PATH}/bin/elasticsearch-setup-passwords auto --batch --verbose --url https://master-0-node.elastic.autoip.dcos.thisdcos.directory:1025'
    register: results

  - name: Parse passwords
    set_fact:
      elastic_password: "{{ results.stdout | regex_search(regexp_elastic,'\\1') }}"
      kibana_password: "{{ results.stdout | regex_search(regexp_kibana,'\\1') }}"
    vars:
      regexp_elastic: 'PASSWORD elastic = (.*)'
      regexp_kibana: 'PASSWORD kibana = (.*)'

  - name: Update Elastic with health credentials
    dcos_package:
      name: elastic
      app_id: elastic
      version: 2.7.0-6.8.1
      state: present
      options:
        {
            "service": {
                "service_account": "elastic",
                "service_account_secret": "elastic/secret",
                "security": {
                    "transport_encryption": {
                        "enabled": true
                    }
                }
            }, 
            "elasticsearch": {
              "health_user": "elastic",
              "health_user_password": "{{ elastic_password | first }}",
              "xpack_enabled": true,
              "xpack_security_enabled": true
            },
            "ingest_nodes": {
              "count": 1
            }  
        }

  - name: Ensure Kibana is installed
    dcos_package:
      name: kibana
      app_id: kibana
      version: 2.7.0-6.8.1
      state: present
      options:
        {
            "kibana": {
                "xpack_enabled": true,
                "elasticsearch_tls": true,
                "elasticsearch_xpack_security_enabled": true,
                "user": "kibana",
                "password": "{{ kibana_password | first }}",
                "elasticsearch_url": "https://coordinator.elastic.l4lb.thisdcos.directory:9200"
            }
        }
