---
- name: Install Kubectl Proxy via Edge-LB
  hosts: localhost
  serial: 1
  become: false
  tasks:

  - name: Connect to the cluster
    include: connection.yml

  - name: Install Edge-LB
    include: edgelb.yml

  - name: Assign permissions for pool kubectl-proxy to Edge-LB
    dcos_iam_group:
      gid: edgelb-group
      description: Permissions for Edge-LB
      state: present
      permissions:
        - rid: dcos:adminrouter:service:dcos-edgelb/pools/kubectl-proxy
          action: full

  - name: Create kubectl-proxy pool
    dcos_edgelb:
      pool_id: kubectl-proxy
      state: present
      options:
        {
          "apiVersion": "V2",
          "name": "kubectl-proxy",
          "cpus": 0.7,
          "count": 1,
          "haproxy": {
            "frontends": [
              {
                "bindPort": 8181,
                "protocol": "TCP",
                "linkBackend": {
                  "defaultBackend": "kubernetes-apiserver"
                }
              }
            ],
            "backends": [{
              "name": "kubernetes-apiserver",
              "protocol": "TCP",
              "services": [{
                "mesos": {
                  "frameworkName": "kubernetes-cluster",
                  "taskNamePattern": "kube-control-plane"
                },
                "endpoint": {
                  "portName": "apiserver"
                }
              }]
            }],
            "stats": {
              "bindPort": 6090
            }
          }
        }